---
title: "FlexDashboard of Wong et al (2001) Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    
---

```{r setup }
library(flexdashboard)
library(car)
data(Wong)
#library(shiny)
library(dplyr)
library(ggplot2)
library(rsconnect)
```
```{r}
Wong$durgrp <- case_when(
  (Wong$duration <= 0) ~ 1,
  (Wong$duration > 0 & Wong$duration <= 2) ~ 2,
  (Wong$duration > 2 & Wong$duration <= 4) ~ 3,
  (Wong$duration > 4 & Wong$duration <= 6) ~ 4,
  (Wong$duration > 6 & Wong$duration <= 8) ~ 5,
  (Wong$duration > 8 & Wong$duration <= 10) ~ 6,
  (Wong$duration > 10 & Wong$duration <= 12) ~ 7,
  (Wong$duration > 12 & Wong$duration <= 14) ~ 8,
   (Wong$duration > 14 & Wong$duration <= 16) ~ 9,
  (Wong$duration > 16 & Wong$duration <= 18) ~ 10,
  (Wong$duration > 18 & Wong$duration <= 20) ~ 11,
  (Wong$duration > 20 & Wong$duration <= 50) ~ 12,
  (Wong$duration > 50 & Wong$duration <= 100) ~ 13,
  (Wong$duration > 100 ) ~ 14)
Wong$durgroup <- factor(Wong$durgrp,
                  levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14),
                  labels = c("<24 hours",
                             "1-2 day",
                             "3-4 days",
                             "5-6 days",
                             "7-8 days",
                             "9-10 days",
                             "11-12 days",
                             "13-14 days",
                             "15-16 days",
                             "17-18 days",
                             "19-20 days",
                             "20-49 days",
                             "50-99 days",
                           "100+ days"))

Wong$durgraph <- factor(Wong$durgrp,
                  levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14),
                  labels = c("<1",
                             "1-2",
                             "3-4",
                             "5-6",
                             "7-8",
                             "9-10",
                             "11-12",
                             "13-14",
                             "15-16",
                             "17-18",
                             "19-20",
                             "20-49",
                             "50-99",
                           "100+"))

Wong$meanIQ <- ((Wong$viq+Wong$piq)/2)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Summary of IQ Outcome Measures by Coma Duration

```{r}
ByDur<-Wong %>% 
  group_by(durgroup) %>%
  summarise(MeanPIQ = mean(piq, na.rm=TRUE),
            SDPIQ = sd(piq, na.rm=TRUE), 
            MeanVIQ = mean(viq, na.rm=TRUE),
            SDVIQ = sd(viq, na.rm=TRUE))

knitr::kable(x = ByDur[1:5],
             col.names = c("Duration of Coma",
                           "Mean Performance IQ",
                           "Standard Deviation of Performance IQ",
                           "Mean Verbal IQ",
                           "Standard Deviation of Verbal IQ"))

```

Column {.tabset}
-----------------------------------------------------------------------

### PIQ score based on duration of Coma

```{r}
Wong %>% 
  #select(sex, duration, piq) %>%
  group_by(durgraph) %>%
  ggplot(aes(x=durgraph, y=piq)) +
  geom_boxplot()  +
  xlab("Duration of Coma (days)") +
  ylab("Performance IQ Score")

Wong %>% 
  ggplot(aes(x=duration, y=piq)) +
  geom_point() +
  geom_smooth(model=lm(piq ~ duration, data = Wong)) +
  xlab("Duration of Coma (days)")+
  ylab("Performance IQ Score")
```


### VIQ score based on duration of Coma

```{r}
Wong %>% 
  #select(sex, duration, piq) %>%
  group_by(durgraph) %>%
  ggplot(aes(x=durgraph, y=viq)) +
  geom_boxplot() +
  xlab("Duration of Coma (days)")+
  ylab("Verbal IQ Score")

Wong %>% 
  ggplot(aes(x=duration, y=viq)) +
  geom_point() +
  geom_smooth(model=lm(viq ~ duration, data = Wong)) +
  xlab("Duration of Coma (days)")+
  ylab("Verbal IQ Score")
```

### MeanIQ score based on duration of Coma

```{r}
Wong %>% 
  #select(sex, duration, piq) %>%
  group_by(durgraph) %>%
  ggplot(aes(x=durgraph, y=meanIQ)) +
  geom_boxplot()  +
  xlab("Duration of Coma (days)")+
  ylab("Mean IQ Score")

Wong %>% 
  ggplot(aes(x=duration, y=meanIQ)) +
  geom_point() +
  geom_smooth(model=lm(meanIQ ~ duration, data = Wong)) +
  xlab("Duration of Coma (days)")+
  ylab("Mean IQ Score")
```
  

